services:

  dev.login.apcode.com.br:
    image: ghcr.io/andrepenteado/apsso/login
    container_name: login
    hostname: login
    environment:
      LOGIN_SERVER: http://dev.login.apcode.com.br:30000
      DB_SERVER: dev.db.apcode.com.br
      ZIPKIN_SERVER: http://cluster.apcode.com.br
    ports:
      - 30000:30000

  dev.controle.apcode.com.br:
    image: ghcr.io/andrepenteado/apsso/controle
    container_name: controle
    hostname: controle
    environment:
      LOGIN_SERVER: http://dev.login.apcode.com.br:30000
      DB_SERVER: dev.db.apcode.com.br
      CLIENT_ID: DEV.com.github.andrepenteado.apsso.controle
      ZIPKIN_SERVER: http://cluster.apcode.com.br
    ports:
      - 30001:8080

  dev.portal.apcode.com.br:
    image: ghcr.io/andrepenteado/apsso/portal
    container_name: portal
    hostname: portal
    environment:
      LOGIN_SERVER: http://dev.login.apcode.com.br:30000
      DB_SERVER: dev.db.apcode.com.br
      CLIENT_ID: DEV.com.github.andrepenteado.apsso.portal
      ZIPKIN_SERVER: http://cluster.apcode.com.br
    ports:
      - 30002:8080

  dev.db.apcode.com.br:
    image: postgres:16
    container_name: postgresql
    hostname: postgresql
    environment:
      POSTGRES_USER: apsso-dbuser
      POSTGRES_PASSWORD: apsso-dbpasswd
      POSTGRES_DB: apsso-dbname
    volumes:
      - apsso-pgdata:/var/lib/postgresql/data/
    ports:
      - 5432:5432

volumes:
  apsso-pgdata:
