services:

  dev.login.apcode.com.br:
    image: ghcr.io/andrepenteado/apsso/login
    container_name: login
    hostname: login
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - 30000:30000
    networks:
      - docker-host-network

  dev.controle.apcode.com.br:
    image: ghcr.io/andrepenteado/apsso/controle
    container_name: controle
    hostname: controle
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - 30001:8080
    networks:
      - docker-host-network

  dev.portal.apcode.com.br:
    image: ghcr.io/andrepenteado/apsso/portal
    container_name: portal
    hostname: portal
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - 30002:8080
    networks:
      - docker-host-network

networks:
  docker-host-network:
    external: true
