version: "3.9"

services:

  login:
    image: ghcr.io/andrepenteado/apsso/login
    hostname: login
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      rollback_config:
        order: start-first
      update_config:
        failure_action: rollback
        order: start-first
      labels:
        - traefik.enable=true
        - traefik.http.routers.login.rule=Host(`login.apcode.com.br`)
        - traefik.http.routers.login.entrypoints=web
        - traefik.http.routers.login.tls=false
        - traefik.http.services.login.loadbalancer.server.port=30000
        - traefik.http.services.login.loadbalancer.sticky=true
        - traefik.http.services.login.loadbalancer.sticky.cookie.name=login-server
        - traefik.http.services.login.loadbalancer.sticky.cookie.httpOnly=true
    environment:
      CATALINA_OPTS: -XX:+UseG1GC -Duser.language=pt -Duser.country=BR -Duser.timezone=GMT-3 -Djava.awt.headless=true
      LOGIN_SERVER: http://login.apcode.com.br
      DB_SERVER: db.apcode.com.br
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - rede-swarm-apsso

  controle:
    image: ghcr.io/andrepenteado/apsso/controle
    hostname: controle
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      rollback_config:
        order: start-first
      update_config:
        failure_action: rollback
        order: start-first
      labels:
        - traefik.enable=true
        - traefik.http.routers.controle.rule=Host(`controle.apcode.com.br`)
        - traefik.http.routers.controle.entrypoints=web
        - traefik.http.routers.controle.tls=false
        - traefik.http.services.controle.loadbalancer.server.port=8080
        - traefik.http.services.controle.loadbalancer.sticky=true
        - traefik.http.services.controle.loadbalancer.sticky.cookie.name=controle-server
        - traefik.http.services.controle.loadbalancer.sticky.cookie.httpOnly=true
    environment:
      JAVA_OPTS: -XX:+UseG1GC -Duser.language=pt -Duser.country=BR -Duser.timezone=GMT-3 -Djava.awt.headless=true
      LOGIN_SERVER: http://login.apcode.com.br
      DB_SERVER: db.apcode.com.br
      CLIENT_ID: com.github.andrepenteado.apsso.controle
      ZIPKIN_SERVER: http://cluster.apcode.com.br
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - rede-swarm-apsso

  portal:
    image: ghcr.io/andrepenteado/apsso/portal
    hostname: portal
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      rollback_config:
        order: start-first
      update_config:
        failure_action: rollback
        order: start-first
      labels:
        - traefik.enable=true
        - traefik.http.routers.portal.rule=Host(`portal.apcode.com.br`)
        - traefik.http.routers.portal.entrypoints=web
        - traefik.http.routers.portal.tls=false
        - traefik.http.services.portal.loadbalancer.server.port=8080
        - traefik.http.services.portal.loadbalancer.sticky=true
        - traefik.http.services.portal.loadbalancer.sticky.cookie.name=portal-server
        - traefik.http.services.portal.loadbalancer.sticky.cookie.httpOnly=true
    environment:
      JAVA_OPTS: -XX:+UseG1GC -Duser.language=pt -Duser.country=BR -Duser.timezone=GMT-3 -Djava.awt.headless=true
      LOGIN_SERVER: http://login.apcode.com.br
      DB_SERVER: db.apcode.com.br
      CLIENT_ID: com.github.andrepenteado.apsso.portal
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - rede-swarm-apsso

networks:
  rede-swarm-apsso:
    external: true
