services:

  login:
    image: ghcr.io/andrepenteado/apsso/login
    container_name: login
    hostname: login
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - 30000:8080
    networks:
      - docker-host-network

  controle-backend:
    image: ghcr.io/andrepenteado/apsso/controle/backend
    container_name: controle-backend
    hostname: controle-backend
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - 30001:8080
    networks:
      - docker-host-network

  controle-frontend:
    image: ghcr.io/andrepenteado/apsso/controle/frontend
    container_name: controle-frontend
    hostname: controle-frontend
    ports:
      - 40001:8080
    networks:
      - docker-host-network

  portal-backend:
    image: ghcr.io/andrepenteado/apsso/portal/backend
    container_name: portal-backend
    hostname: portal-backend
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - 30002:8080
    networks:
      - docker-host-network

  portal-frontend:
    image: ghcr.io/andrepenteado/apsso/portal/frontend
    container_name: portal-frontend
    hostname: portal-frontend
    ports:
      - 40002:8080
    networks:
      - docker-host-network

networks:
  docker-host-network:
    external: true
