---
apiVersion: v1
kind: Namespace
metadata:
  name: apsso

---
apiVersion: v1
kind: Secret
metadata:
  name: github-secret
  namespace: apsso
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJZVzVrY21Wd1pXNTBaV0ZrYnpwbmFIQmZORTgxVmtWWlIzZGhkbUo1VjJOcE1uQlhWV2MxV21ad1IyeEZibXR6TURkWWJEaEgiCgkJfQoJfSwKCSJhbGlhc2VzIjogewoJCSJidWlsZGVyIjogImJ1aWxkeCIKCX0KfQ==
type: kubernetes.io/dockerconfigjson

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appso-login
  namespace: apsso
  labels:
    apsso.apcode.com.br/modulo: login
spec:
  replicas: 1
  selector:
    matchLabels:
      apsso.apcode.com.br/modulo: login
  template:
    metadata:
      labels:
        apsso.apcode.com.br/modulo: login
    spec:
      containers:
        - name: appso-login
          image: ghcr.io/andrepenteado/apsso/login
          imagePullPolicy: Always
          ports:
            - containerPort: 30000
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
      hostAliases:
        - ip: 200.145.157.33
          hostnames:
            - postgresql
      imagePullSecrets:
      - name: github-secret

---
apiVersion: v1
kind: Service
metadata:
  name: appso-login
  namespace: apsso
  labels:
    apsso.apcode.com.br/modulo: login
spec:
  type: LoadBalancer
  ports:
    - name: appso-login
      port: 30000
      targetPort: 30000
  selector:
    apsso.apcode.com.br/modulo: login

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apsso
  namespace: apsso
spec:
  rules:
    - http:
        paths:
          - path: /sso
            pathType: Prefix
            backend:
              service:
                name: appso-login
                port:
                  name: appso-login
