spring:

  datasource:
    url: jdbc:postgresql://db-server:5433/apsso-dbname?autoReconnect=true
    username: apsso-dbuser
    password: apsso-dbpasswd
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  tracing:
    enabled: false

frontend:
  pagina-inicial: https://equipe.apcode.com.br