spring:

  application:
    name: equipe

  datasource:
    url: jdbc:postgresql://db.apcode.com.br/apsso-dbname?autoReconnect=true
    username: apsso-dbuser
    password: apsso-dbpasswd
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: equipe-pool

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
        boot:
          use_jdbc_metadata_defaults: false

  security:
    oauth2:
      client:
        registration:
          "[com.github.andrepenteado.sso.equipe]":
            provider: com.github.andrepenteado.sso.portal
            client-name: Gestão de Equipes
            client-id: PRODUCAO-equipe
            client-secret: b72fa3f1-9dc5-47c9-882c-8710e3565db5
            authorization-grant-type: authorization_code
            scope: openid
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: client_secret_basic
        provider:
          "[com.github.andrepenteado.sso.portal]":
            issuer-uri: https://login.apcode.com.br

server:
  forward-headers-strategy: framework
  port: 8080
  error:
    include-message: always
  servlet:
    context-path: /equipe-backend

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://sistemas.apcode.com.br:9411

frontend:
  pagina-inicial: https://sistemas.apcode.com.br/equipe/pagina-inicial