spring:
  datasource:
    url: jdbc:postgresql://db-server/apsso-dbname

  security:
    oauth2:
      client:
        registration:
          "[com.github.andrepenteado.sso.equipe]":
            provider: com.github.andrepenteado.sso.portal
            client-name: Gestão de Equipes
            client-id: LOCAL-equipe
            client-secret: 82f6a88a-4c7c-4432-937b-3997aa621675
            authorization-grant-type: authorization_code
            scope: openid
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: client_secret_basic
        provider:
          "[com.github.andrepenteado.sso.portal]":
            issuer-uri: http://localhost:30000

management:
  tracing:
    enabled: false

frontend:
  pagina-inicial: http://localhost:4200/equipe/pagina-inicial