spring:

  datasource:
    url: jdbc:postgresql://${DB_SERVER}/apsso-dbname?autoReconnect=true
    username: apsso-dbuser
    password: apsso-dbpasswd
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: portal-pool

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
        temp:
          use_jdbc_metadata_defaults: false

  security:
    oauth2:
      client:
        registration:
          portal-oidc:
            provider: spring
            client-id: ${CLIENT_ID}
            client-secret: portal-secret
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: portal-oidc
        provider:
          spring:
            issuer-uri: ${LOGIN_SERVER}

server:
  error:
    include-message: always