spring:

  application:
    name: controle

  datasource:
    url: jdbc:postgresql://db.apcode.com.br/apsso-dbname?autoReconnect=true
    username: apsso-dbuser
    password: apsso-dbpasswd
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: controle-pool

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
        boot:
          allow_jdbc_metadata_access: false

  security:
    oauth2:
      client:
        registration:
          "[com.github.andrepenteado.sso.controle]":
            provider: com.github.andrepenteado.sso.portal
            client-name: Módulo de Controle
            client-id: com.github.andrepenteado.sso.controle
            client-secret: 9c9dcb57-c306-494b-bb83-47565e1163a4
            authorization-grant-type: authorization_code
            scope: openid
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: client_secret_basic
        provider:
          "[com.github.andrepenteado.sso.portal]":
            issuer-uri: https://login.apcode.com.br

server:
  forward-headers-strategy: framework
  port: 8080
  error:
    include-message: always
  servlet:
    context-path: /controle-backend

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://sistemas.apcode.com.br:9411

frontend:
  pagina-inicial: https://sistemas.apcode.com.br/controle/pagina-inicial