# Instalar os dependências para usar os módulos ansible para kubernetes
#
# ansible-galaxy collection install kubernetes.core
# Ter instalado o python-kubernetes (ou pip install kubernetes)

- name: Fazer deploy do sistema no kubernetes
  hosts: localhost

  tasks:

  - name: Fazendo deploy dos serviços
    kubernetes.core.k8s:
      state: present
      src: 04-deployment.yml

  - name: Expondo serviços
    kubernetes.core.k8s:
      state: present
      src: 05-ingress.yml