- name: Instalar APsso e seus componentes
  hosts: localhost
  vars:
    diretorio:
      raiz: /opt

  tasks:
  - name: Criar diretório do traefik
    ansible.builtin.file:
      path: "{{ diretorio.raiz }}/traefik"
      state: directory

  - name: Copiar docker-compose do traefik
    ansible.builtin.copy:
      src: swarm/traefik.yml
      dest: "{{ diretorio.raiz }}/traefik/docker-compose.yml"

  - name: Baixar imagem do traefik
    community.docker.docker_image:
      name: traefik
      source: pull

  - name: Criar diretório do APsso
    ansible.builtin.file:
      path: "{{ diretorio.raiz }}/apsso"
      state: directory

  - name: Copiar Makefile
    ansible.builtin.copy:
      src: swarm/Makefile
      dest: "{{ diretorio.raiz }}/apsso/"

  - name: Copiar docker-compose do APsso para diretório de stacks de serviços
    ansible.builtin.copy:
      src: swarm/apsso.yml
      dest: "{{ diretorio.raiz }}/apsso/docker-compose.yml"

  - name: Criar rede interna docker
    community.docker.docker_network:
      name: rede-swarm-apsso
      driver: overlay
      attachable: yes
