# Instalar os dependências para usar os módulos ansible para kubernetes
#
# ansible-galaxy collection install kubernetes.core
# Ter instalado o python-kubernetes (ou pip install kubernetes)

- name: Fazer deploy do sistema no kubernetes
  hosts: localhost

  tasks:

  - name: Deploy dos módulos do sistema
    kubernetes.core.k8s:
      state: present
      src: kubernetes-apsso.yml
