# Instalar os dependências para usar os módulos ansible para kubernetes
#
# ansible-galaxy collection install kubernetes.core
# Ter instalado o python-kubernetes (ou pip install kubernetes)

- name: Fazer deploy do sistema no kubernetes
  hosts: localhost
  vars:
    diretorio:
      raiz: /home/andrepenteado

  tasks:
  - name: Criar namespace do sistema
    kubernetes.core.k8s:
      state: present
      src: namespace.yml

  - name: Criar secret do github
    kubernetes.core.k8s:
      state: present
      src: secret.yml

  - name: Deploy do módulo de login
    kubernetes.core.k8s:
      state: present
      src: login.yml
