apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apsso
  namespace: apsso
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
    - secretName: cert-apcode.com.br
  rules:
    - host: login.apcode.com.br
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: apsso-login
                port:
                  name: apsso-login
    - host: api-controle.apcode.com.br
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: apsso-controle-backend
                port:
                  name: control-back
    - host: api-portal.apcode.com.br
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: apsso-portal-backend
                port:
                  name: portal-back
    - host: controle.apcode.com.br
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: apsso-controle-frontend
                port:
                  name: control-front
    - host: portal.apcode.com.br
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: apsso-portal-frontend
                port:
                  name: portal-front
