services:

  login:
    image: ghcr.io/andrepenteado/apsso/login
    container_name: login
    hostname: login
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - 30000:30000
    networks:
      - docker-host-network

  controle-backend:
    image: ghcr.io/andrepenteado/apsso/controle-backend
    container_name: controle-backend
    hostname: controle-backend
    environment:
      SPRING_PROFILES_ACTIVE: dev
      AUTHORIZATION_SERVER_URL: http://login:30000
    ports:
      - 30001:8080
    networks:
      - docker-host-network

  controle-frontend:
    image: ghcr.io/andrepenteado/apsso/controle-frontend:dev
    container_name: controle-frontend
    hostname: controle-frontend
    ports:
      - 40001:80
    networks:
      - docker-host-network

  portal-backend:
    image: ghcr.io/andrepenteado/apsso/portal-backend
    container_name: portal-backend
    hostname: portal-backend
    environment:
      SPRING_PROFILES_ACTIVE: dev
      AUTHORIZATION_SERVER_URL: http://login:30000
    ports:
      - 30002:8080
    networks:
      - docker-host-network

  portal-frontend:
    image: ghcr.io/andrepenteado/apsso/portal-frontend:dev
    container_name: portal-frontend
    hostname: portal-frontend
    ports:
      - 40002:80
    networks:
      - docker-host-network

  equipe-backend:
    image: ghcr.io/andrepenteado/apsso/equipe-backend
    container_name: equipe-backend
    hostname: equipe-backend
    environment:
      SPRING_PROFILES_ACTIVE: dev
      AUTHORIZATION_SERVER_URL: http://login:30000
    ports:
      - 30003:8080
    networks:
      - docker-host-network

  equipe-frontend:
    image: ghcr.io/andrepenteado/apsso/portal-equipe:dev
    container_name: equipe-frontend
    hostname: equipe-frontend
    ports:
      - 40003:80
    networks:
      - docker-host-network

volumes:
  apsso-pgdata:
  apsso-test-pgdata:

networks:
  docker-host-network:
    external: true
