services:

  controle-frontend:
    image: ghcr.io/andrepenteado/apsso/controle-frontend:dev
    container_name: controle-frontend
    hostname: controle-frontend
    ports:
      - 40001:80
    networks:
      - docker-host-network

  portal-frontend:
    image: ghcr.io/andrepenteado/apsso/portal-frontend:dev
    container_name: portal-frontend
    hostname: portal-frontend
    ports:
      - 40002:80
    networks:
      - docker-host-network

  equipe-frontend:
    image: ghcr.io/andrepenteado/apsso/portal-equipe:dev
    container_name: equipe-frontend
    hostname: equipe-frontend
    ports:
      - 40003:80
    networks:
      - docker-host-network

networks:
  docker-host-network:
    external: true
