spring:
  datasource:
    url: jdbc:postgresql://dbserver/apsso-dbname

  security:
    oauth2:
      client:
        provider:
          portal-de-sistemas:
            issuer-uri: http://localhost:30000

management:
  tracing:
    enabled: false

frontend:
  pagina-inicial: http://localhost:4200/portal/pagina-inicial