# Stage 1
# Build
FROM maven:3-amazoncorretto-21-debian AS build
WORKDIR /apsso/
COPY pom.xml /apsso/
COPY /login/pom.xml /apsso/login/
COPY /controle/ /apsso/controle/
RUN mvn --projects backend -U clean package --file /apsso/pom.xml -DskipTests

# Stage 2
# Deploy
FROM amazoncorretto:21
WORKDIR /backend
COPY --from=build /apsso/controle/target/backend.jar /controle/controle.jar
ENTRYPOINT [ "java", "-jar", "-Dserver.port=30001", "/controle/controle.jar" ]
EXPOSE 30001
