services:

  login:
    image: ghcr.io/andrepenteado/apsso/login
    container_name: login
    hostname: login
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - 30000:30000

  controle:
    image: ghcr.io/andrepenteado/apsso/controle
    container_name: controle
    hostname: controle
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - 30001:30001

  postgresql:
    image: postgres:15.2
    container_name: postgresql
    hostname: postgresql
    environment:
      POSTGRES_USER: apsso-dbuser
      POSTGRES_PASSWORD: apsso-dbpasswd
      POSTGRES_DB: apsso-dbname
    volumes:
      - apsso-pgdata:/var/lib/postgresql/data/
    command: -p 50000
    ports:
      - 50000:50000

volumes:
  apsso-pgdata:
