# Stage 1 - Angular
FROM node:20 AS angular
WORKDIR /app
COPY /frontend/portal/ /app/frontend/portal/
RUN npm --prefix ./frontend/portal install
RUN npm --prefix ./frontend/portal run build --omit=dev

# Stage 2 - Deploy
FROM nginx
WORKDIR /site
COPY --from=angular /app/frontend/portal/dist/  /usr/share/nginx/html/
EXPOSE 80