# Stage 1
# Build
FROM maven:3-amazoncorretto-21-debian AS build
WORKDIR /apsso/
COPY pom.xml /apsso/
COPY /login/pom.xml /apsso/login/
COPY /backend/ /apsso/backend/
RUN mvn --projects backend -U clean package --file /apsso/pom.xml -DskipTests

# Stage 2
# Deploy
FROM amazoncorretto:21
WORKDIR /backend
COPY --from=build /apsso/backend/target/backend.jar /backend/backend.jar
ENTRYPOINT [ "java", "-jar", "/backend/backend.jar" ]
EXPOSE 30001