services:

  dev.db.apcode.com.br:
    image: postgres:16
    container_name: apsso-db
    hostname: apsso-db
    environment:
      POSTGRES_USER: apsso-dbuser
      POSTGRES_PASSWORD: apsso-dbpasswd
      POSTGRES_DB: apsso-dbname
    volumes:
      - apsso-pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - docker-host-network

  dev.db-test.apcode.com.br:
    image: postgres:16
    container_name: apsso-db-test
    hostname: apsso-db-test
    environment:
      POSTGRES_USER: apsso-dbuser
      POSTGRES_PASSWORD: apsso-dbpasswd
      POSTGRES_DB: apsso-dbname
    volumes:
      - apsso-test-pgdata:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - docker-host-network

volumes:
  apsso-pgdata:
  apsso-test-pgdata:

networks:
  docker-host-network:
    external: true
