spring:

  datasource:
    url: jdbc:postgresql://localhost:50000/apsso-dbname?autoReconnect=true
    username: apsso-dbuser
    password: apsso-dbpasswd
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: sso-pool

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  output:
    ansi:
      enabled: always
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration

server:
  port: 30000
  error:
    whitelabel:
      enabled: false
  servlet:
    context-path: /sso

# keytool.exe -genkeypair -alias apsso -keyalg RSA -keypass passwebra -keystore apsso.jks -storepass passwebra
apsso:
  uri: "http://localhost:30000/sso"
  jks:
    keypass: passwebra
    storepass: passwebra
    alias: apsso
    path: apsso.jks
