spring:

  datasource:
    url: jdbc:postgresql://apsso-db:50000/apsso-dbname?autoReconnect=true
    username: apsso-dbuser
    password: apsso-dbpasswd
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: apsso-pool

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false

  security:
    oauth2:
      client:
        registration:
          apsso-oidc:
            provider: spring
            client-id: com.github.andrepenteado.apsso
            client-secret: apsso-secret
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: apsso-oidc
        provider:
          spring:
            issuer-uri: http://apsso:30000

server:
  port: 30001
  error:
    include-message: always