spring:
  datasource:
    url: jdbc:postgresql://db-server/apsso-dbname

management:
  tracing:
    enabled: false

apsso:
  uri: http://localhost:30000
  urlPortal: http://localhost:4200/portal/login
