spring:

  application:
    name: login

  datasource:
    url: jdbc:postgresql://db.apcode.com.br/apsso-dbname?autoReconnect=true
    username: apsso-dbuser
    password: apsso-dbpasswd
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: sso-pool

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        boot:
          allow_jdbc_metadata_access: false

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  output:
    ansi:
      enabled: always
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration

server:
  forward-headers-strategy: framework
  error:
    whitelabel:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://sistemas.apcode.com.br:9411

# keytool.exe -genkeypair -alias apsso -keyalg RSA -keypass passwebra -keystore apsso.jks -storepass passwebra
apsso:
  uri: https://login.apcode.com.br
  jks:
    keypass: passwebra
    storepass: passwebra
    alias: apsso
    path: apsso.jks
