name: Compilar, testar e buildar o backend

on: workflow_dispatch
#on:
#  push:
#    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest
    name: Buildar, testar e gerar imagem

    services:
      dev.db-test.apcode.com.br:
        image: postgres:16
        env:
          POSTGRES_DB: apsso-dbname
          POSTGRES_USER: apsso-dbuser
          POSTGRES_PASSWORD: apsso-dbpasswd
        ports:
          - 5433:5432

    steps:

      - name: Checkout do projeto
        uses: actions/checkout@v3

      - name: Usar JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: 'maven'

      - name: Definir settings.xml
        uses: s4u/maven-settings-action@v2.8.0
        with:
          servers: |
            [{
                "id": "github-apcode",
                "username": "${{ github.actor }}",
                "password": "${{ secrets.GITHUB_TOKEN }}"
            }]

      - name: Compilar e testar os m처dulos do projeto
        run: mvn -B --file ./backend/pom.xml clean package
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Buscar vers찾o atual
        run: echo "VERSAO=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout --file ./backend/pom.xml)" >> $GITHUB_ENV

      - name: Logar no registry do github
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build da imagem docker do login
        run: docker build -f .docker/dockerfiles/login -t ghcr.io/andrepenteado/apsso/login:latest -t ghcr.io/andrepenteado/apsso/login:${{ env.VERSAO }} .

      - name: Push da imagem docker do login
        run: |
          docker push ghcr.io/andrepenteado/apsso/login:latest
          docker push ghcr.io/andrepenteado/apsso/login:${{ env.VERSAO }}

      - name: Build da imagem docker do backend do m처dulo de controle
        run: docker build -f .docker/dockerfiles/backend.controle -t ghcr.io/andrepenteado/apsso/controle-backend:latest -t ghcr.io/andrepenteado/apsso/controle-backend:${{ env.VERSAO }} .

      - name: Push da imagem docker do backend do m처dulo de controle
        run: |
          docker push ghcr.io/andrepenteado/apsso/controle-backend:latest
          docker push ghcr.io/andrepenteado/apsso/controle-backend:${{ env.VERSAO }}

      - name: Build da imagem docker do backend do portal de sistemas
        run: docker build -f .docker/dockerfiles/backend.portal -t ghcr.io/andrepenteado/apsso/portal-backend:latest -t ghcr.io/andrepenteado/apsso/portal-backend:${{ env.VERSAO }} .

      - name: Push da imagem docker do backend do portal de sistemas
        run: |
          docker push ghcr.io/andrepenteado/apsso/portal-backend:latest
          docker push ghcr.io/andrepenteado/apsso/portal-backend:${{ env.VERSAO }}
