name: Compilar, testar e buildar

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest
    name: Buildar, testar e gerar imagem

    services:
      apsso-db-test:
        image: postgres:15.2
        env:
          POSTGRES_DB: apsso-dbname
          POSTGRES_USER: apsso-dbuser
          POSTGRES_PASSWORD: apsso-dbpasswd
        ports:
          - 54320:5432

    steps:

      - name: Checkout do projeto
        uses: actions/checkout@v3

      - name: Usar Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Instalar pacotes do frontend do módulo administrativo
        run: npm --prefix ./frontend install

      - name: Buildar frontend do módulo administrativo
        run: npm --prefix ./frontend run build --omit=dev

      - name: Usar JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'maven'

      - name: Compilar e testar os módulos do projeto projeto
        run: mvn -B clean package

      - name: Buscar versão atual
        run: echo "VERSAO=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout --file pom.xml)" >> $GITHUB_ENV

      - name: Logar no registry do github
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build da imagem docker do login
        run: docker build -f .docker/Dockerfile.pipeline -t ghcr.io/andrepenteado/apsso/apsso:latest -t ghcr.io/andrepenteado/apsso/apsso:${{ env.VERSAO }} .

      - name: Push da imagem docker do login
        run: |
          docker push ghcr.io/andrepenteado/apsso/apsso:latest
          docker push ghcr.io/andrepenteado/apsso/apsso:${{ env.VERSAO }}

      - name: Build da imagem docker do backend do módulo administrativo
        run: docker build -f .docker/Dockerfile.backend.pipeline -t ghcr.io/andrepenteado/apsso/apsso-backend:latest -t ghcr.io/andrepenteado/apsso/apsso-backend:${{ env.VERSAO }} .

      - name: Push da imagem docker do backend do módulo administrativo
        run: |
          docker push ghcr.io/andrepenteado/apsso/apsso-backend:latest
          docker push ghcr.io/andrepenteado/apsso/apsso-backend:${{ env.VERSAO }}