name: Compilar, testar e buildar

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest
    name: Buildar, testar e gerar imagem

    steps:

      - name: Checkout do projeto
        uses: actions/checkout@v3

      - name: Usar JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'maven'

      - name: Buscar versão atual
        run: echo "VERSAO=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout --file pom.xml)" >> $GITHUB_ENV

      - name: Logar no registry do github
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build da imagem docker
        run: docker build -f Dockerfile -t ghcr.io/andrepenteado/apsso/apsso:latest -t ghcr.io/andrepenteado/apsso/apsso:${{ env.VERSAO }} .

      - name: Push da imagem docker
        run: |
          docker push ghcr.io/andrepenteado/apsso/apsso:latest
          docker push ghcr.io/andrepenteado/apsso/apsso:${{ env.VERSAO }}
