name: Compilar, testar e buildar

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest
    name: Buildar, testar e gerar imagem

    services:
      dev.db-test.apcode.com.br:
        image: postgres:16
        env:
          POSTGRES_DB: apsso-dbname
          POSTGRES_USER: apsso-dbuser
          POSTGRES_PASSWORD: apsso-dbpasswd
        ports:
          - 5433:5432

    steps:

      - name: Checkout do projeto
        uses: actions/checkout@v3

      - name: Usar Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Criar arquivo .npmrc
        run: echo -e "@andrepenteado:registry=https://npm.pkg.github.com\n//npm.pkg.github.com/:_authToken=//registry.npmjs.org/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc

      - name: Instalar pacotes do frontend do módulo de controle
        run: npm --prefix ./frontend/controle install

      - name: Buildar frontend do módulo de controle
        run: npm --prefix ./frontend/controle run build --omit=dev -- "-c=production"

      - name: Instalar pacotes do frontend do portal de sistemas
        run: npm --prefix ./frontend/portal install

      - name: Buildar frontend do portal de sistemas
        run: npm --prefix ./frontend/portal run build --omit=dev -- "-c=production"

      - name: Usar JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: 'maven'

      - name: Definir settings.xml
        uses: s4u/maven-settings-action@v2.8.0
        with:
          servers: |
            [{
                "id": "github-apcode",
                "username": "${{ github.actor }}",
                "password": "${{ secrets.GITHUB_TOKEN }}"
            }]

      - name: Compilar e testar os módulos do projeto
        run: mvn -B clean package
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Buscar versão atual
        run: echo "VERSAO=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout --file ./backend/pom.xml)" >> $GITHUB_ENV

      - name: Logar no registry do github
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build da imagem docker do login
        run: docker build -f .docker/Dockerfile.login.pipeline -t ghcr.io/andrepenteado/apsso/login:latest -t ghcr.io/andrepenteado/apsso/login:${{ env.VERSAO }} .

      - name: Push da imagem docker do login
        run: |
          docker push ghcr.io/andrepenteado/apsso/login:latest
          docker push ghcr.io/andrepenteado/apsso/login:${{ env.VERSAO }}

      - name: Build da imagem docker do módulo de controle
        run: docker build -f .docker/Dockerfile.controle.pipeline -t ghcr.io/andrepenteado/apsso/controle:latest -t ghcr.io/andrepenteado/apsso/controle:${{ env.VERSAO }} .

      - name: Push da imagem docker do módulo de controle
        run: |
          docker push ghcr.io/andrepenteado/apsso/controle:latest
          docker push ghcr.io/andrepenteado/apsso/controle:${{ env.VERSAO }}

      - name: Build da imagem docker do portal de sistemas
        run: docker build -f .docker/Dockerfile.portal.pipeline -t ghcr.io/andrepenteado/apsso/portal:latest -t ghcr.io/andrepenteado/apsso/portal:${{ env.VERSAO }} .

      - name: Push da imagem docker do portal de sistemas
        run: |
          docker push ghcr.io/andrepenteado/apsso/portal:latest
          docker push ghcr.io/andrepenteado/apsso/portal:${{ env.VERSAO }}
